### PR TITLE
Remove bot detection mediator

### PR DESCRIPTION
**Pull request by ruks**
- Remove bot detection mediator
- Fixed https://github.com/wso2/product-apim/issues/9985

### CODE REVIEW

**Review by fazlan-nazeem — APPROVED** [review]

**Comment by bhathiya** [comment]
Why did we remove bot detection mediator?

**Comment by ruks** [comment]
> Why did we remove bot detection mediator?

Bot detection is based on SP analytics and still cloud analytics not support it. Hence removing since we removed all the SP data publishing. Will include it back when cloud analytics support this.

**Comment by ruks** [comment]
Depends on https://github.com/wso2/carbon-apimgt/pull/9903

**Comment by tishan89** [comment]
@ruks Let's keep the mediator but only remove the data publishing part

**Comment by ruks** [comment]
Close this PR and re-adding bot detection mediator with the PR https://github.com/wso2/carbon-apimgt/pull/9905.

**Pull request closed without merging**
